#ifndef _SPRD_PUBEFUSE_SHARKLE_H_
#define _SPRD_PUBEFUSE_SHARKLE_H_

#define SECURE_BOOT_BLOCK_1 (92)
#define SECURE_BOOT_BLOCK_2 ((SECURE_BOOT_BLOCK_1) + (1))
#define SECURE_BOOT_BIT (0)

#define PTEST_BLOCK_1 (92)
#define PTEST_BLOCK_2 ((PTEST_BLOCK_1) + (1))
#define DISABLE_PTEST (13)

#endif
